force-app/main/default/objects/Assignment_History__c/Assignment_History__c.object-meta.xml
<CustomObject>
    <label>Assignment History</label>
    <nameField>
        <displayFormat>AH-{0000}</displayFormat>
        <label>Assignment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assignment History</relationshipLabel>
    <relationshipName>Assignment_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Assignment_History__c/fields/Changed_By__c.field-meta.xml
<CustomField>
    <fullName>Changed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Changed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_History2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment_History__c/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_History1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment_History__c/fields/New_Territory__c.field-meta.xml
<CustomField>
    <fullName>New_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Assignment History (New Territory)</relationshipLabel>
    <relationshipName>Assignment_History1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment_History__c/fields/Previous_Owner__c.field-meta.xml
<CustomField>
    <fullName>Previous_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment_History__c/fields/Previous_Territory__c.field-meta.xml
<CustomField>
    <fullName>Previous_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Assignment History</relationshipLabel>
    <relationshipName>Assignment_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateOwnersQueueable.cls
public class UpdateOwnersQueueable implements Queueable {
    private List<Territory__c> ters;
    public UpdateOwnersQueueable(List<Territory__c> ters){
        this.ters=ters;
    }
    public void execute(System.QueueableContext context){
        List<account> UpdateList = new List<Account>();
        List<Assignment_History__C> insertList = new List<Assignment_History__C>();
        map<String, Territory__c> mapZipCodetoTerritory  = new map<string,Territory__c>();

        //Attach transaction Finalizer
        AssignmentHistoryFinalizer f =  new AssignmentHistoryFinalizer();
        system.attachFinalizer(f);


        for(Territory__c t: ters){
            if(!mapZipCodetoTerritory.isEmpty()){
                if(!mapZipCodetoTerritory.containsKey(t.Zip_Code__c)){
                    mapZipCodetoTerritory.put(t.Zip_Code__c,t);
                }
            }else{
                mapZipCodetoTerritory.put(t.Zip_Code__c,t);
            }
        }
        System.debug('In Queueable'+mapZipCodetoTerritory);
          for(account acc: [select id,BillingPostalCode,OwnerId,Territory__c from account where BillingPostalCode in : mapZipCodetoTerritory.keySet()])  
          {
            Assignment_History__C aHistory = new Assignment_History__C();
            aHistory.Previous_Owner__c = acc?.ownerId;
            aHistory.Previous_Territory__c = acc?.Territory__c;

              acc.OwnerId = mapZipCodetoTerritory.get(acc.BillingPostalCode).OwnerId;
              acc.Territory__c = mapZipCodetoTerritory.get(acc.BillingPostalCode).Id;
              UpdateList.add(acc);

             aHistory.New_Territory__c = mapZipCodetoTerritory.get(acc.BillingPostalCode).Id;
             aHistory.new_Owner__c = mapZipCodetoTerritory.get(acc.BillingPostalCode).OwnerId;
             aHistory.Changed_By__c =UserInfo.getUserId();
             aHistory.Account__c = acc.Id;
             f.createInsertList(aHistory);
          }
          If(UpdateList!=null && !UpdateList.isEmpty()){
            update UpdateList;
        }
        //     If(insertList!=null && !insertList.isEmpty()){
        //     insert insertList;
        // }
    }
}