force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TerritoryValidations.cls
public with sharing class TerritoryValidations {
        Public Static void redundantZipCodes(List<string> zipcodes,List<Territory__c> tList){
               map<string,Integer> zipCountMap = new map<string,Integer>(); 
             for(AggregateResult result: [select Zip_Code__c,Count(Id) from Territory__c where Zip_Code__c in:zipcodes group by Zip_Code__c]){
                 zipCountMap.put((string) result.get('Zip_Code__c'), (Integer)result.get('expr0'));
             }
            for(Territory__c t: tList){
                    if(zipCountMap.get(t.Zip_Code__c)>=3){
                        t.addError('Only 3 records per zip code can be created');
                    }
            }
            
        }

    }